<?php
echo "<!DOCTYPE HTML>
<html lang='en'>
   <head>
      <meta charset='utf-8'>
      <title>Registration Success</title>
      <link rel='stylesheet' href='css/normalize.css'>
      <link rel='stylesheet' href='css/style.css'>
   </head>
   <body>
      <h1>Registration Success</h1>
      <p>You’ve successfully registered. Click <a href='./index.php?action=login'>here</a> to go back to the home page and log in, or you can simply wait 5 seconds to be redirected.</p>
   </body>
</html>
";
